name: Linting, Testing and Danger Review

on:
  pull_request:
    branches: [main, develop]

  workflow_dispatch:

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Linting Rules
        run: npm run lint

  Testing:
    needs: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps
        
      - name: Run Unit Tests
        run: npm run test

  #
  Danger-Review:
    needs: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Load & Cache Dependencies
        uses: ./.github/actions/cached-deps

      - name: Set up Git and run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.DANGER_CI_TOKEN }}
        run: |
          git config --global user.name 'danger_ci_bot'
          git config --global user.email 'demirtasdurmus@gmail.com'
          npm run danger:ci